### ISSUE TITLE
Stuck in loop checking CPU scheduling classification when trying to run performance suite.

### ISSUE THREAD

**Issue by joeldavis84** [test-network-function/cnf-certification-test#1101] opened 2023-05-18 00:04 UTC
When running either 4.2.3 or 4.2.4 I get stuck in the following loop if I ever enable to `performance` suite:

    INFO   [May 17 23:50:36.219][scheduling.go: 120] Checking the scheduling policy/priority in container: xxx-xxxxxx pod: xxx-xxxxxx-xxxxxxx-xxxxx-2qwv5 ns: xxxxxx for pid=368 
    INFO   [May 17 23:50:36.438][scheduling.go: 133] pid 368 in container: xxx-xxxxxx pod: xxx-xxxxxx-xxxxxxx-xxxxx-2qwv5 ns: xxxxxx has the cpu scheduling policy SCHED_FIFO, scheduling priority 99 
      pid=368 in container: xxx-xxxxxx pod: xxx-xxxxxx-xxxxxxx-xxxxx-2qwv5 ns: xxxxxx with cpu scheduling policy=SCHED_FIFO, priority=%!s(int=99) did not satisfy cpu scheduling requirements
    INFO   [May 17 23:50:36.438][scheduling.go: 120] Checking the scheduling policy/priority in container: xxx-xxxxxx pod: xxx-xxxxxx-xxxxxxx-xxxxx-2qwv5 ns: xxxxxx for pid=369 
    INFO   [May 17 23:50:36.649][scheduling.go: 133] pid 369 in container: xxx-xxxxxx pod: xxx-xxxxxx-xxxxxxx-xxxxx-2qwv5 ns: xxxxxx has the cpu scheduling policy SCHED_FIFO, scheduling priority 99 
      pid=369 in container: xxx-xxxxxx pod: xxx-xxxxxx-xxxxxxx-xxxxx-2qwv5 ns: xxxxxx with cpu scheduling policy=SCHED_FIFO, priority=%!s(int=99) did not satisfy cpu scheduling requirements
    INFO   [May 17 23:50:36.649][scheduling.go: 120] Checking the scheduling policy/priority in container: xxx-xxxxxx pod: xxx-xxxxxx-xxxxxxx-xxxxx-2qwv5 ns: xxxxxx for pid=370 
    INFO   [May 17 23:50:36.848][scheduling.go: 133] pid 370 in container: xxx-xxxxxx pod: xxx-xxxxxx-xxxxxxx-xxxxx-2qwv5 ns: xxxxxx has the cpu scheduling policy SCHED_OTHER, scheduling priority 0 
      pid=370 in container: xxx-xxxxxx pod: xxx-xxxxxx-xxxxxxx-xxxxx-2qwv5 ns: xxxxxx with cpu scheduling policy=SCHED_OTHER, priority=%!s(int=0) satisfies cpu scheduling requirements
    INFO   [May 17 23:50:36.848][scheduling.go: 120] Checking the scheduling policy/priority in container: xxx-xxxxxx pod: xxx-xxxxxx-xxxxxxx-xxxxx-2qwv5 ns: xxxxxx for pid=372 
    INFO   [May 17 23:50:37.056][scheduling.go: 133] pid 372 in container: xxx-xxxxxx pod: xxx-xxxxxx-xxxxxxx-xxxxx-2qwv5 ns: xxxxxx has the cpu scheduling policy SCHED_OTHER, scheduling priority 0 
      pid=372 in container: xxx-xxxxxx pod: xxx-xxxxxx-xxxxxxx-xxxxx-2qwv5 ns: xxxxxx with cpu scheduling policy=SCHED_OTHER, priority=%!s(int=0) satisfies cpu scheduling requirements
    INFO   [May 17 23:50:37.056][scheduling.go: 120] Checking the scheduling policy/priority in container: xxx-xxxxxx pod: xxx-xxxxxx-xxxxxxx-xxxxx-2qwv5 ns: xxxxxx for pid=373 
    INFO   [May 17 23:50:37.261][scheduling.go: 133] pid 373 in container: xxx-xxxxxx pod: xxx-xxxxxx-xxxxxxx-xxxxx-2qwv5 ns: xxxxxx has the cpu scheduling policy SCHED_OTHER, scheduling priority 0 
      pid=373 in container: xxx-xxxxxx pod: xxx-xxxxxx-xxxxxxx-xxxxx-2qwv5 ns: xxxxxx with cpu scheduling policy=SCHED_OTHER, priority=%!s(int=0) satisfies cpu scheduling requirements
    INFO   [May 17 23:50:37.261][scheduling.go: 120] Checking the scheduling policy/priority in container: xxx-xxxxxx pod: xxx-xxxxxx-xxxxxxx-xxxxx-2qwv5 ns: xxxxxx for pid=374 
    INFO   [May 17 23:50:37.475][scheduling.go: 133] pid 374 in container: xxx-xxxxxx pod: xxx-xxxxxx-xxxxxxx-xxxxx-2qwv5 ns: xxxxxx has the cpu scheduling policy SCHED_FIFO, scheduling priority 99 
      pid=374 in container: xxx-xxxxxx pod: xxx-xxxxxx-xxxxxxx-xxxxx-2qwv5 ns: xxxxxx with cpu scheduling policy=SCHED_FIFO, priority=%!s(int=99) did not satisfy cpu scheduling requirements
    INFO   [May 17 23:50:37.475][scheduling.go: 120] Checking the scheduling policy/priority in container: xxx-xxxxxx pod: xxx-xxxxxx-xxxxxxx-xxxxx-2qwv5 ns: xxxxxx for pid=375 
    INFO   [May 17 23:50:37.685][scheduling.go: 133] pid 375 in container: xxx-xxxxxx pod: xxx-xxxxxx-xxxxxxx-xxxxx-2qwv5 ns: xxxxxx has the cpu scheduling policy SCHED_FIFO, scheduling priority 99 
      pid=375 in container: xxx-xxxxxx pod: xxx-xxxxxx-xxxxxxx-xxxxx-2qwv5 ns: xxxxxx with cpu scheduling policy=SCHED_FIFO, priority=%!s(int=99) did not satisfy cpu scheduling requirements

And then it just goes on like that (it will run until interrupted, I've let it runf or close to half an hour before) until I issue a `oc delete ds -n cnf-suite` to delete the test pods which causes the execution to kick forward (likely with additional errors, I'd presume). I redacted the namespace and pod names for the sake of confidentiality.

**Comment by AbhishekBandarupalle** [comment] 2023-05-20 13:51
To provide more context about the pods under test: All of them are privileged - making the number of processes accessed from within the pod much higher.

**Comment by bnshr** [comment] 2023-05-24 14:54
The issue is solved by skipping tests if the pods have access to the host system.

**Comment by mwlinca** [comment] 2023-06-08 00:45
can this be closed now?

**Comment by bnshr** [comment] 2023-06-08 10:35
@joeldavis84 @AbhishekBandarupalle Can we please close this issue?

**Comment by joeldavis84** [comment] 2023-06-08 17:04
OK yeah I just ran a new version of the test suite and it didn't get caught in the loop and the tests are skipping now.

**Closed** 2023-06-09 13:22 UTC
